### ISSUE TITLE
Activity User Journey CSV 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app-backend#1217]
We need to track the movement of the user throughout the web and mobile app 

Track button presses 
- Next Undo and back buttons should be tracked for all item types including markdown 
- Tracking should be on mobile and web 
- A separate CSV called User Journey should be exported everytime the admin exports 
Fields Must have:
- ID 
- Activity Scheduled
- Activity Start
- Activity End 
- Press Next time 
- Press Undo time
- Press Back time 
- Response option selection time 
- Secret User ID 
- User ID 
- Activity ID 
- Activity Name
- Item Name
- Prompt
- Options 
- Version 

If there are other fields that would be good, please add

**Comment by natalia-muzyka** [comment]
@WorldImpex 
1 - response column is missing in the activity_user_journey.csv, I assume this is correct because we collect only the latest response (attachment), right?
2 - cognitive tasks are out of the scope?

**Comment by WorldImpex** [comment]
1. Yes the admin can retrieve that from the other file
2. No, they are in scope

**Comment by natalia-muzyka** [comment]
**ISSUES:**
Rejecting the "Response submit" duplicates in the report the last item option selection time #1580
Only the last response option selection is recorded and displayed in the report #1578
Tap on the "Done" button on the "Summary" screen is recorded as a new press_next_time of the last item #1575
Time out is recorded as a Response selection time (replaces the actual selection time if there was a selection made) #1574
[A/B trails] Tapping the "Next" button is recorded only on the practice screen (tap on the instructions is not recorded) #1573

**Fixed**
Tap on the "Skip" is recorded as the press_next #1572
There is the "response_option_time" column name instead of the "response_option_selection_time" in the report#1571

**Backlogged** 
One page assessment issues #1579

**Comment by natalia-muzyka** [comment]
@WorldImpex @jj105  the "hit_next_time" column is missing now in the general report,
there was no such a requirement, is it acceptable as we have now the same info in the Activity user journey CSV?

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/10117607-1b8f-4f44-b684-3eaa7e6dbe22)

**Comment by WorldImpex** [comment]
Yes I think so @natalia-muzyka

**Comment by natalia-muzyka** [comment]
Verified and closed. Checked on:
ML v0.20.10 staging
ML v0.20.15 staging
iPhone XR // iOS 14.3
Samsung Galaxy S7 // Android 8
Google Pixel 5a // Android 11
Samsung Galaxy Tab S6 SM-T865 // Android  9.0
iPad Air 2 WiFi // iOS 14.6
Apple iPad 9th gen (2021) / iOS 15.5
https://admin-staging.mindlogger.org/
https://web-staging.mindlogger.org/
Win 10 / Chrome 102
macOS 10.15 / Chrome 102
